### PR TITLE
Change: Pressing Button Also Triggers Music Change

### PR DESCRIPTION
**Pull request by 6819710**
Disabled Music Manager script in Game Manager (See Slack)
Moved Music Object out of Game Manager as it is a stand alone object.

### CODE REVIEW

**Comment by 6819710** [comment]
[Music Trigger: Calm](https://trello.com/c/KI1poVZr/33-music-trigger-calm)

**Comment by 6819710** [comment]
Buttons have to refernce object in unity file, cannot add changes directly to prefab (look at button settings)

this is due to implementation of exsisting trigger, as I said before trigger both causes state change and music change

startbutton

**Comment by xxfast** [comment]
Changes to the unity file is going to cause lots of merge issues :/ remember the last time?

**Comment by 6819710** [comment]
It only causes issues if this is not resolved before other changes need to be made, the rule is One change at a time, this is the only trigger that needs to be refenced from the unity file, again note that I am not changing any code, simply adding the message on button click, its the same as the game state manager (as evidance in image) as I disussed with you on slack, this is a trigger to an event, the trigger both changes the state of the game (in the scene) and the state of the music.

**Pull request merged**
